language: ruby
rvm:
- 2.5.1
script:
- bundle exec rails db:migrate
- bundle exec rspec -fd spec
deploy:
  provider: heroku
  api_key:
    secure: A01KWqt39s0DUEl2vKDpezzV/29bs2tosD/jK4nPjWJEg0a8d1v6ZEYyZraguSXg+derbPQxW6oCJOKfER5Acew7mCpCtmvUjMSWLWRkMJPC0eW1KKVqF36NBHhGIEO4Q9xb8gSsLBErZ3ULzSs7VuDgRtzaTqFdfl/GP7rknpcNteZPkiSdJkd0CFGag5NHrZh+RhWyJpidhuWcyC04ehuaglmwgbOBKlsG0dszalfDoXEVm+NUYT8joRvTvYgzsuwvJoJRjGkcJ2c80L+SrTnJiswCnu+1c7V6GwvR7CIKpv8jV66C5NVZClAmPo1rf1fxZHRRYfQZdpwsroLESya4naOeIYiCARuwKE3FY9UFmMub1Vvcbsbrd07blBqLw2yC9zK5/PXvqcpi6ReVM7CFw9V9822hWU8GZH5MJ3Nf8q3RsYni+07FOw2C2sVogiYQbGE7HocPjQjXhBaNdBov0AnVyj49yVYt+AeNb+MBMchz/aTnenyzS+l21rq29aFsc2moe7zCsbKg2PN+4f70O5JHUB8f2Odk+a69hwVcxiEViPUd8b9HDeCePFNvV1tpuOk1SHummqReKQddiUNbgIdkzEgmKkAQ2XiqkOAFapvMcKmsyargAIhTW4O4zj+OUwLh83mZkaWWGtIz78VebYqZbGSHmPm0dl63P2E=
  app: dry-brushlands-93333
  on:
    repo: VoxWave/ratebeer
