language: ruby
rvm:
- 2.5.1
script:
- bundle exec rails db:migrate
- bundle exec rspec -fd spec
deploy:
  provider: heroku
  api_key:
    secure: HeL2AJ8+Y+cSdlSlaNl8YudB/qaJBO2kUrJOJO+tyvaT6BnPgu6u8HEIQUgLYv05VAwOXY0axnbtP4Sohf/p4ozxiRGB1i042YmnngMmQHMgAXbYo5DpIO31WOTZG2tQzfIvP2Qguwu+n5y+oLY73CVKQVhn6KG/dLwnx2Ds+kuJRLwqhTJGyyVzfswzuO2kT4qYu/RT5KoXYOp15iDDrQXnlX4R/IcAuKOP3B7jgfFu+FMZCbVX+dZAkv64jStEbohgWmpfHkHsMCrrEqoj60j8SopVws82keEs5oCgYfTKHw1pNERkJ1GLj9fLUKXj9KNfBTpSPgj1hQYLQx0jcb+jx8xmSWF6qUpE9zf6PobOaYnQBoU44S+vseBVWAipC27SwM9p2vOsjsLWwLDvS19Yy6hKP50AuZxXwT2xmMiV309TuYKjltIbLan4Qa0r64CNwIWCyJxK1swYdZQk1n90/zjXi/PAxquWgP03uNUoxJbxTTQ1OJA3CnhTU/UULoFo6vKG+sxckxnEp6wMrFblY2hJHBpu7BQ9FDTmvaRpeTtkNWbHIv7EsmVn1NoY6TgggEOLrLTRWY0TBS3FJArpkTsCpZodrDMwa5wgSFT6/WCZ3B0uIyau5KNQh9JnjlK+BWDnwymLXtH2fJAWUvwCPvS/CAHCVsNqx/HQe4M=
  app: ratebeer
  on:
    repo: VoxWave/ratebeer
  run: "rails db:migrate"
